from base_exception import BaseException


class P2PValidationFailException(BaseException):
    pass
